export const FILTER_OPERATORS = [
  { label: 'Contains', value: 'CONTAINS', filterFor: 'string' },
  { label: '>=', value: 'GTE', filterFor: 'number' },
  { label: '<=', value: 'LTE', filterFor: 'number' },
  { label: 'Equals', value: 'EQ', filterFor: 'boolean' },
];

export const FILTER_IDS = [
  { label: 'Name', value: 'name' },
  { label: 'Screen Name', value: 'screen_name' },
  { label: 'Followers Count', value: 'followers_count' },
  { label: 'Following Count', value: 'following_count' },
  { label: 'Location', value: 'location' },
  { label: 'Verified', value: 'verified' },
];

export const FILTER_TYPES = {
  name: 'string',
  screen_name: 'string',
  followers_count: 'number',
  following_count: 'number',
  location: 'string',
  verified: 'boolean',
};

export const CONDITIONS = [
  { label: 'AND', value: 'AND' },
  { label: 'OR', value: 'OR' },
];

export const TABLE_DATA = [
  {
    name: 'Renaldo Ca',
    screen_name: 'rca0',
    followers_count: 726,
    following_count: 752,
    location: 'Peru',
    verified: true,
  },
  {
    name: 'Bobbette Dibling',
    screen_name: 'bdibling1',
    followers_count: 747,
    following_count: 613,
    location: 'Argentina',
    verified: true,
  },
  {
    name: 'Obed Snelson',
    screen_name: 'osnelson2',
    followers_count: 466,
    following_count: 352,
    location: 'Russia',
    verified: false,
  },
  {
    name: 'Elyssa Eastop',
    screen_name: 'eeastop3',
    followers_count: 888,
    following_count: 493,
    location: 'Uganda',
    verified: true,
  },
  {
    name: 'Auroora Balogun',
    screen_name: 'abalogun4',
    followers_count: 688,
    following_count: 468,
    location: 'Brazil',
    verified: true,
  },
  {
    name: 'Sarge Crosser',
    screen_name: 'scrosser5',
    followers_count: 218,
    following_count: 424,
    location: 'United Kingdom',
    verified: true,
  },
  {
    name: 'Griswold Lardeur',
    screen_name: 'glardeur6',
    followers_count: 785,
    following_count: 122,
    location: 'South Korea',
    verified: false,
  },
  {
    name: 'Edwin Goodlatt',
    screen_name: 'egoodlatt7',
    followers_count: 484,
    following_count: 611,
    location: 'Indonesia',
    verified: true,
  },
  {
    name: 'Brannon Lethby',
    screen_name: 'blethby8',
    followers_count: 652,
    following_count: 523,
    location: 'Ukraine',
    verified: false,
  },
  {
    name: 'Lemmy Siegertsz',
    screen_name: 'lsiegertsz9',
    followers_count: 135,
    following_count: 370,
    location: 'United States',
    verified: true,
  },
  {
    name: 'Maxie Carpenter',
    screen_name: 'mcarpentera',
    followers_count: 798,
    following_count: 516,
    location: 'Philippines',
    verified: false,
  },
  {
    name: 'Natalee Sedger',
    screen_name: 'nsedgerb',
    followers_count: 138,
    following_count: 422,
    location: 'China',
    verified: false,
  },
  {
    name: 'Bale Renny',
    screen_name: 'brennyc',
    followers_count: 681,
    following_count: 210,
    location: 'China',
    verified: false,
  },
  {
    name: 'Patty Riche',
    screen_name: 'priched',
    followers_count: 363,
    following_count: 204,
    location: 'China',
    verified: false,
  },
  {
    name: 'Spenser Pockett',
    screen_name: 'spockette',
    followers_count: 469,
    following_count: 604,
    location: 'Kazakhstan',
    verified: false,
  },
  {
    name: 'Leigh Goghin',
    screen_name: 'lgoghinf',
    followers_count: 333,
    following_count: 590,
    location: 'Philippines',
    verified: false,
  },
  {
    name: 'Dick Greguoli',
    screen_name: 'dgreguolig',
    followers_count: 599,
    following_count: 631,
    location: 'Portugal',
    verified: false,
  },
  {
    name: 'Neely Barnard',
    screen_name: 'nbarnardh',
    followers_count: 752,
    following_count: 187,
    location: 'China',
    verified: false,
  },
  {
    name: 'Loy Farrah',
    screen_name: 'lfarrahi',
    followers_count: 131,
    following_count: 323,
    location: 'China',
    verified: false,
  },
  {
    name: 'Abran Burnand',
    screen_name: 'aburnandj',
    followers_count: 695,
    following_count: 389,
    location: 'Madagascar',
    verified: false,
  },
  {
    name: 'Elinore Reeveley',
    screen_name: 'ereeveleyk',
    followers_count: 179,
    following_count: 572,
    location: 'Indonesia',
    verified: false,
  },
  {
    name: 'Barny Flindall',
    screen_name: 'bflindalll',
    followers_count: 202,
    following_count: 319,
    location: 'Mexico',
    verified: true,
  },
  {
    name: 'Hamish Tassel',
    screen_name: 'htasselm',
    followers_count: 37,
    following_count: 361,
    location: 'Nigeria',
    verified: false,
  },
  {
    name: 'Jenelle Upstell',
    screen_name: 'jupstelln',
    followers_count: 882,
    following_count: 531,
    location: 'Peru',
    verified: false,
  },
  {
    name: 'Gaynor Himpson',
    screen_name: 'ghimpsono',
    followers_count: 358,
    following_count: 913,
    location: 'Syria',
    verified: true,
  },
  {
    name: 'Lucky Dole',
    screen_name: 'ldolep',
    followers_count: 782,
    following_count: 943,
    location: 'Norway',
    verified: false,
  },
  {
    name: 'Isador Griffe',
    screen_name: 'igriffeq',
    followers_count: 41,
    following_count: 359,
    location: 'China',
    verified: true,
  },
  {
    name: 'Thea Rubberts',
    screen_name: 'trubbertsr',
    followers_count: 438,
    following_count: 125,
    location: 'France',
    verified: true,
  },
  {
    name: 'Chickie Ewells',
    screen_name: 'cewellss',
    followers_count: 544,
    following_count: 922,
    location: 'France',
    verified: false,
  },
  {
    name: 'Britt Vanelli',
    screen_name: 'bvanellit',
    followers_count: 34,
    following_count: 892,
    location: 'Brazil',
    verified: true,
  },
  {
    name: 'Kelwin Hatherley',
    screen_name: 'khatherleyu',
    followers_count: 49,
    following_count: 701,
    location: 'Mali',
    verified: true,
  },
  {
    name: 'Dell Venturoli',
    screen_name: 'dventuroliv',
    followers_count: 9,
    following_count: 949,
    location: 'China',
    verified: true,
  },
  {
    name: 'Winonah Mandal',
    screen_name: 'wmandalw',
    followers_count: 283,
    following_count: 540,
    location: 'Kazakhstan',
    verified: false,
  },
  {
    name: 'Annabell Twinborne',
    screen_name: 'atwinbornex',
    followers_count: 402,
    following_count: 589,
    location: 'United States',
    verified: false,
  },
  {
    name: 'Georgianna Newvell',
    screen_name: 'gnewvelly',
    followers_count: 552,
    following_count: 593,
    location: 'China',
    verified: false,
  },
  {
    name: 'Lefty Feake',
    screen_name: 'lfeakez',
    followers_count: 638,
    following_count: 747,
    location: 'Russia',
    verified: true,
  },
  {
    name: 'Kariotta Varvell',
    screen_name: 'kvarvell10',
    followers_count: 319,
    following_count: 208,
    location: 'Portugal',
    verified: false,
  },
  {
    name: 'Dody MacClancey',
    screen_name: 'dmacclancey11',
    followers_count: 327,
    following_count: 677,
    location: 'Greece',
    verified: false,
  },
  {
    name: 'Theodor Hasselby',
    screen_name: 'thasselby12',
    followers_count: 617,
    following_count: 164,
    location: 'United States',
    verified: false,
  },
  {
    name: "Viviana L'Hommee",
    screen_name: 'vlhommee13',
    followers_count: 252,
    following_count: 67,
    location: 'China',
    verified: true,
  },
  {
    name: 'Hercule Beardsall',
    screen_name: 'hbeardsall14',
    followers_count: 513,
    following_count: 652,
    location: 'China',
    verified: false,
  },
  {
    name: 'Cinnamon Plover',
    screen_name: 'cplover15',
    followers_count: 321,
    following_count: 839,
    location: 'Georgia',
    verified: true,
  },
  {
    name: 'Virgina Reijmers',
    screen_name: 'vreijmers16',
    followers_count: 114,
    following_count: 451,
    location: 'Georgia',
    verified: true,
  },
  {
    name: 'Tades Kolushev',
    screen_name: 'tkolushev17',
    followers_count: 534,
    following_count: 643,
    location: 'United States',
    verified: false,
  },
  {
    name: 'Sasha Du Plantier',
    screen_name: 'sdu18',
    followers_count: 506,
    following_count: 623,
    location: 'Russia',
    verified: false,
  },
  {
    name: 'Melantha Filchakov',
    screen_name: 'mfilchakov19',
    followers_count: 324,
    following_count: 778,
    location: 'South Africa',
    verified: true,
  },
  {
    name: 'Margarette Abbyss',
    screen_name: 'mabbyss1a',
    followers_count: 644,
    following_count: 706,
    location: 'Uzbekistan',
    verified: true,
  },
  {
    name: 'Katha Fallowes',
    screen_name: 'kfallowes1b',
    followers_count: 234,
    following_count: 132,
    location: 'Brazil',
    verified: false,
  },
  {
    name: 'Arlin Schistl',
    screen_name: 'aschistl1c',
    followers_count: 101,
    following_count: 657,
    location: 'Indonesia',
    verified: true,
  },
  {
    name: 'Henka Perren',
    screen_name: 'hperren1d',
    followers_count: 170,
    following_count: 422,
    location: 'Mexico',
    verified: true,
  },
];
